spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: mottu_flyway_schema_history
    baseline-version: 0

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.fiap: DEBUG
    org.flywaydb: INFO

jwt:
  secret: mottuSecretKey2024Sprint3JavaAdvancedFIAP
  expiration: 5184000000 # 2 meses em milissegundos (60 dias)

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
